# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twitter-followers-histogram}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karmen Blake"]
  s.date = %q{2010-09-18}
  s.description = %q{Histogram showing the amount of followers your followers have}
  s.email = %q{karmenblake@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/twitter-followers-histogram.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/twitter-followers-histogram_spec.rb",
     "twitter-followers-histogram.gemspec"
  ]
  s.homepage = %q{http://github.com/kblake/twitter-followers-histogram}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Histogram showing the amount of followers your followers have}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/twitter-followers-histogram_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

